server:
  servlet:
    context-path: /
  port:
    8080
spring:
  profiles:
    active:
      - ${ACTIVE_SPRING_PROFILE:dev}
  application:
    name: api-gateway-service
springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        primaryName: API Gateway Service
      - url: /product-service/v3/api-docs
        name: Product Service
        primaryName: Product Service
      - url: /price-service/v3/api-docs
        name: Price Service
        primaryName: Price Service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
---
spring:
  config:
    activate:
      on-profile: local

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
---

spring:
  config:
    activate:
      on-profile: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
---
spring:
  config:
    activate:
      on-profile: prod

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false